package view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.text.Text;
import model.vo.UsuarioVO;
import javafx.scene.control.TextField;
import controller.ControladoraUsuario;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FXMLUsuarioAtualizarController {
	@FXML
	private Button btnCadastrarUsuario;
	@FXML
	private TextField txtNome;
	@FXML
	private TextField txtCPF;
	@FXML
	private TextField txtTelefone;
	@FXML
	private TextField txtLogin;
	@FXML
	private TextField txtSenha;
	@FXML
	private Text lblCPF;
	@FXML
	private Text lblTelefone;
	@FXML
	private Text lblLogin;
	@FXML
	private Text lblSenha;
	@FXML
	private TextField txtCodigo;
	@FXML
	private Label lblAviso;
	@FXML
	private Button btnVoltar;
	@FXML
	private Text lblTitulo;

	// Event Listener on Button.onAction
	@FXML
	public void loadUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadReceita(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCadastrarUsuario].onAction
	@FXML
	public void atualizarUsuario(ActionEvent event) {
		UsuarioVO usuarioVO = new UsuarioVO();
		
		usuarioVO.setIdUsuario(Integer.parseInt(txtCodigo.getText()));
		usuarioVO.setNome(txtNome.getText());
		usuarioVO.setCpf(txtCPF.getText());
		usuarioVO.setTelefone(txtTelefone.getText());
		usuarioVO.setLogin(txtLogin.getText());
		usuarioVO.setSenha(txtSenha.getText());
		
		ControladoraUsuario controladoraUsuario = new ControladoraUsuario();
		controladoraUsuario.atualizarUsuarioController(usuarioVO);

		txtCodigo.setText("");
		txtNome.setText("");
		txtCPF.setText("");
		txtTelefone.setText("");
		txtLogin.setText("");
		txtSenha.setText("");
		
	}
	// Event Listener on Button[#btnVoltar].onAction
	@FXML
	public void voltarUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
}
