package view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.text.Text;
import model.vo.UsuarioVO;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import controller.ControladoraUsuario;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class FXMLUsuarioConsultarTodosController implements Initializable{
	@FXML
	private Button btnConsultarUsuarios;
	@FXML
	private Button btnVoltar;
	@FXML
	private Text lblTitulo;
	@FXML
	private TableView<UsuarioVO> tblTabela;
	@FXML
	private TableColumn<UsuarioVO, String> clnCod;
	@FXML
	private TableColumn<UsuarioVO, String> clnNome;
	@FXML
	private TableColumn<UsuarioVO, String> clnCPF;
	@FXML
	private TableColumn<UsuarioVO, String> clnTelefone;

	private List<UsuarioVO> listaUsuariosVO = new ArrayList();
	

	
	private ObservableList<UsuarioVO> observableListUsuarios;
	
	public void carregarTableViewUsuarios() {
		ControladoraUsuario controladoraUsuario = new ControladoraUsuario();
		listaUsuariosVO = controladoraUsuario.consultarTodosUsuariosController();
//		
//		UsuarioVO u1 = new UsuarioVO( 1, "Maick", "062524242","991686182", "MM", "SS");
//		UsuarioVO u2 = new UsuarioVO( 1, "Janis", "062524242","991686182", "MM", "SS");
//		listaUsuariosVO.add(u1);
//		listaUsuariosVO.add(u2);
		
		observableListUsuarios = FXCollections.observableArrayList(listaUsuariosVO);
		clnCod.setCellValueFactory(new PropertyValueFactory<>("idUsuario"));
		clnNome.setCellValueFactory(new PropertyValueFactory<>("nome"));
		clnCPF.setCellValueFactory(new PropertyValueFactory<>("cpf"));
		clnTelefone.setCellValueFactory(new PropertyValueFactory<>("telefone"));

		
		
		
		tblTabela.setItems(observableListUsuarios);
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void loadUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadReceita(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnConsultarUsuarios].onAction
	@FXML
	public void consultarUsuarios(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVoltar].onAction
	@FXML
	public void voltarUsuario(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		carregarTableViewUsuarios();
	}
}
