package view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.text.Text;
import model.vo.DespesaVO;
import model.vo.UsuarioVO;
import javafx.scene.control.TextField;

import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

import controller.ControladoraDespesa;
import controller.ControladoraUsuario;
import javafx.event.ActionEvent;

public class FXMLDespesaConsultarCodDespesaController {
	@FXML
	private Button btnUsuario;
	@FXML
	private Button btnReceita;
	@FXML
	private Button btnDespesa;
	@FXML
	private Button btnRelatorio;
	@FXML
	private Button brnSobre;
	@FXML
	private Button btnVoltar;
	@FXML
	private Button btnConsultarDespesaPorCod;
	@FXML
	private TextField cmbCodigo;
	@FXML
	private Text lblCodReceita;
	@FXML
	private Text lblNomeUsuario;
	@FXML
	private Text lblCodUsuario;
	@FXML
	private Text lblDescricao;
	@FXML
	private Text txtCodUsuario;
	@FXML
	private Text txtDescricao;
	@FXML
	private Text txtNomeUsuario;
	@FXML
	private Text lblData;
	@FXML
	private Text txtDataVencimento;
	@FXML
	private Text lblValor;
	@FXML
	private Text txtValor;
	@FXML
	private Text txtCategoria;
	@FXML
	private Text txtDataPagamento;


	// Event Listener on Button[#btnUsuario].onAction
	@FXML
	public void loadUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReceita].onAction
	@FXML
	public void loadReceita(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDespesa].onAction
	@FXML
	public void loadDespesa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRelatorio].onAction
	@FXML
	public void loadRelatorio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#brnSobre].onAction
	@FXML
	public void loadSobre(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVoltar].onAction
	@FXML
	public void voltarDespesa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnConsultarDespesaPorCod].onAction
	@FXML
	public void consultarDespesaPorCodigo(ActionEvent event) {
		DateTimeFormatter dataFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
		Locale ptBr = new Locale("pt", "BR");
		
		DespesaVO despesaVO = new DespesaVO();
		
		despesaVO.setId(Integer.parseInt(cmbCodigo.getText())); 
		ControladoraDespesa controladoraDespesa = new ControladoraDespesa();
		DespesaVO idDespesa = controladoraDespesa.consultarDespesaCOntroller(despesaVO);
		
		UsuarioVO usuario = new UsuarioVO();
		
		usuario.setIdUsuario(idDespesa.getIdUsuario());
		
		ControladoraUsuario controladoraUsuario = new ControladoraUsuario();
		usuario = controladoraUsuario.consultarUsuarioCOntroller(usuario);
		
		txtCodUsuario.setText(Integer.toString(idDespesa.getIdUsuario()));
		txtNomeUsuario.setText(usuario.getNome());
		txtDescricao.setText(idDespesa.getDescricao());
		txtCategoria.setText(idDespesa.getCategoria());
		txtDataPagamento.setText(idDespesa.getDataPagamento().format(dataFormatter));
		txtDataVencimento.setText(idDespesa.getDataVencimento().format(dataFormatter));
		txtValor.setText(NumberFormat.getCurrencyInstance(ptBr).format(idDespesa.getValor()));
	}
}
