package view;

import javafx.fxml.FXML;

import javafx.scene.text.Text;
import model.vo.UsuarioVO;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import controller.ControladoraUsuario;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FXMLUsuarioExcluirController {
	@FXML
	private TextField txtCodigo;
	@FXML
	private Text lblCodigo;
	@FXML
	private Text lblTitulo;
	@FXML
	private Label lblAviso;
	@FXML
	private Button btnVoltar;
	@FXML
	private Button btnExcluir;

	// Event Listener on Button.onAction
	@FXML
	public void loadUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadReceita(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVoltar].onAction
	@FXML
	public void voltarUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExcluir].onAction
	@FXML
	public void excluirUsuario(ActionEvent event) {
		UsuarioVO usuarioVO = new UsuarioVO();

		usuarioVO.setIdUsuario(Integer.parseInt(txtCodigo.getText()));
		
		ControladoraUsuario controladoraUsuario = new ControladoraUsuario();
		controladoraUsuario.excluirUsuarioController(usuarioVO);
		
		txtCodigo.setText("");
	}
}
