package view;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.text.Text;
import javafx.stage.Stage;
import model.vo.UsuarioVO;
import javafx.scene.control.TextField;

import java.io.IOException;

import controller.ControladoraUsuario;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FXMLUsuarioConsultarUmController {
	@FXML
	private Button btnConsultarUsuario;
	@FXML
	private Text lblCPF;
	@FXML
	private Text lblTelefone;
	@FXML
	private TextField txtCodigo;
	@FXML
	private Text txtCPF;
	@FXML
	private Text txtNome;
	@FXML
	private Text txtTelefone;
	@FXML
	private Label lblAviso;
	@FXML
	private Button btnVoltar;
	@FXML
	private Text lblTitulo;

	// Event Listener on Button.onAction
	@FXML
	public void loadUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadReceita(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnConsultarUsuario].onAction
	@FXML
	public void consultarUsuario(ActionEvent event) {
		UsuarioVO usuarioVO = new UsuarioVO();
		usuarioVO.setIdUsuario(Integer.parseInt(txtCodigo.getText()));
		ControladoraUsuario controladoraUsuario = new ControladoraUsuario();
		UsuarioVO usuario = controladoraUsuario.consultarUsuarioCOntroller(usuarioVO);
		
		txtTelefone.setText(usuario.getTelefone());
		txtNome.setText(usuario.getNome());
		txtCPF.setText(usuario.getCpf());
		
		
		
	}
	// Event Listener on Button[#btnVoltar].onAction
	@FXML
	public void voltarUsuario(ActionEvent event) throws IOException {
		Parent parent = FXMLLoader.load(getClass().getResource("FXMLUsuario.fxml"));
		Scene scene = new Scene(parent, 800, 600);
		Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
		window.setScene(scene);
		window.show();
		
	}
}
