package view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.text.Text;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class FXMLCategoriaController {
	@FXML
	private Button btnUsuario;
	@FXML
	private Button btnReceita;
	@FXML
	private Button btnDespesa;
	@FXML
	private Button btnRelatorio;
	@FXML
	private Button brnSobre;
	@FXML
	private Text lblTitulo;
	@FXML
	//
	private Text lblTitulo1;
	@FXML
	private TextField txtDescricao;
	@FXML
	private Button btnIncluir;
	@FXML
	private Button btnVoltar;
	@FXML
	private ComboBox cmbCodigo;
	@FXML
	private Text lblTitulo11;
	@FXML
	private Button btnExcluir;

	// Event Listener on Button[#btnUsuario].onAction
	@FXML
	public void loadUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReceita].onAction
	@FXML
	public void loadReceita(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDespesa].onAction
	@FXML
	public void loadDespesa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRelatorio].onAction
	@FXML
	public void loadRelatorio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#brnSobre].onAction
	@FXML
	public void loadSobre(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnIncluir].onAction
	@FXML
	public void incluirCategoria(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVoltar].onAction
	@FXML
	public void loadCadastrarDespesa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cmbCodigo].onAction
	@FXML
	public void consultarCategoria(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExcluir].onAction
	@FXML
	public void excluirCategoria(ActionEvent event) {
		// TODO Autogenerated
	}
}
